# Inserts a blank line between shell prompts
add_newline = false
command_timeout = 10000

[directory]
style = "#F8BD96"

[cmd_duration]
style = "#F2CECF"

[git_branch]
style = "#C6AAE8"

[git_state]
style = "#EBDDAA"

[username]
disabled = true

[hostname]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[c]
style = "#f5e0dc"

[character]
success_symbol = "[󰘧](bold green)"
error_symbol = "[󰘧](bold red)"

[python]
# disabled = true
python_binary = "python3"
