#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config insert_feedback_color        ff8474
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config external_bar                 all:35:00

# Window modifications
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

# Window border
borders \
  active_color=0xFFF2D5CF \
  inactive_color=0xFF1E1E2E \
  width=5.0 \
  style=round \
  blacklist="FaceTime,zoom.us,System Preferences,Spotify,Numi" &

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10 
yabai -m config left_padding                 10  
yabai -m config right_padding                10  
yabai -m config window_gap                   15

# Renaming the spaces
yabai -m space 1 --label I
yabai -m space 2 --label II
yabai -m space 3 --label III
yabai -m space 4 --label IV
yabai -m space 5 --label V
yabai -m space 6 --label VI

# Turn off management for certain apps
# yabai -m rule --add app="Alacritty" 
# yabai -m rule --add app="^Brave Browser$" opacity=0.98
yabai -m rule --add app="FaceTime" manage=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="QuickTime Player" manage=off layer=below
yabai -m rule --add app="Quick Camera" manage=off layer=below
yabai -m rule --add app="Zed" opacity=0.95
yabai -m rule --add app="Code" opacity=0.95
yabai -m rule --add app="IntelliJ IDEA" opacity=0.98
yabai -m rule --add app="Rectangle" manage=off
yabai -m rule --add app="VSCodium" opacity=0.95
yabai -m rule --add app="Messages" manage=off
yabai -m rule --add app="Numi" manage=off

# Some Settings For Simple-Bar
yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'" label="Refresh simple-bar on space change"
yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'" label="Refresh simple-bar on display focus change"
yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'" label="Refresh simple-bar when focused application changes"
yabai -m signal --add event=window_resized action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'" label="Refresh simple-bar when a window is resized"
yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'" label="Refresh simple-bar when front application switched application changes"
yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'" label="Refresh simple-bar when an application window is closed"
yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'" label="Refresh simple-bar when current window title changes"
