[flags]
process_memory_as_value = true
tree = true

[processes]
columns = ["PID", "Name", "CPU%", "Mem", "T.Read", "T.Write", "User", "State", "Time"]

[[row]]
    ratio=25
    [[row.child]]
        type="cpu"

[[row]]
    ratio=25
    [[row.child]]
        ratio=50
        type="mem"
    [[row.child]]
        ratio=50
        type="net"

[[row]]
    ratio=50
    [[row.child]]
        type="proc"
        default=true
