# Inserts a blank line between shell prompts
add_newline = false

[directory]
style = "#F8BD96"

[cmd_duration]
style = "#F2CECF"

[git_branch]
style = "#C6AAE8"

[git_state]
style = "#EBDDAA"

[lua]
disabled = true

[character]
success_symbol = "[ﬦ](bold green)"
error_symbol = "[ﬦ](bold red)"

[python]
disabled = true
python_binary = "python3"
